"""Idempotent demo seeding for dependency-free (SQLite) deployments.

On startup the service creates the schema and, if the host table is empty,
inserts a deterministic dataset (6 hosts × 14 days of hourly samples) so the
forecast and recommendation endpoints return meaningful results immediately.
Safe to run on every boot: it no-ops once data exists.

The metric values are generated by :mod:`app.core.workload`, whose archetypes
are calibrated to published datacentre traces (Azure Resource Central SOSP'17,
Alibaba 2018, Barroso & Hölzle) — see ``docs/09_workload_modeling.md``.
"""

from __future__ import annotations

from datetime import UTC, datetime, timedelta
from uuid import uuid4

from sqlalchemy import func, select

from .core import workload
from .db import get_engine, get_sessionmaker
from .models import Action, Base, Host, Metric

_SEED_DAYS = 14  # two full weeks → weekly pattern + a robust expanding backtest

# (hostname, environment, vcpu, memory_mb, archetype_key)
_DEMO_HOSTS = [
    ("web-prod-01", "PROD", 16, 32768, "interactive_web"),     # over-provisioned
    ("api-prod-04", "PROD", 8, 16384, "interactive_api"),      # moderate diurnal
    ("cache-prod-05", "PROD", 8, 65536, "steady_cache"),       # memory-bound
    ("batch-etl-01", "STAGING", 16, 32768, "batch_etl"),       # bursty / delay-insensitive
    ("api-staging-02", "STAGING", 8, 16384, "service_lowutil"),  # heavily over-provisioned
    ("batch-dev-03", "DEV", 4, 8192, "devtest"),               # sporadic dev/test
]


async def create_schema() -> None:
    async with get_engine().begin() as conn:
        await conn.run_sync(Base.metadata.create_all)


async def seed_demo_data() -> int:
    """Insert demo hosts + metrics when the database is empty. Returns rows added."""
    sessionmaker = get_sessionmaker()
    async with sessionmaker() as session:
        existing = await session.scalar(select(func.count()).select_from(Host))
        if existing:
            return 0

        base = datetime(2024, 1, 1, tzinfo=UTC)  # a Monday — aligns the week
        added = 0
        for hostname, env, vcpu, mem, arch_key in _DEMO_HOSTS:
            host = Host(
                id=str(uuid4()),
                hostname=hostname,
                environment=env,
                vcpu_count=vcpu,
                memory_mb=mem,
                created_at=base,
            )
            session.add(host)

            arch = workload.ARCHETYPE_BY_KEY[arch_key]
            samples = workload.generate(arch, days=_SEED_DAYS, seed=hostname)
            for s in samples:
                session.add(
                    Metric(
                        host_id=host.id,
                        ts=base + timedelta(hours=s.hour),
                        cpu_pct=s.cpu_pct,
                        mem_pct=s.mem_pct,
                        net_in_kbps=s.net_in_kbps,
                        net_out_kbps=s.net_out_kbps,
                    )
                )
                added += 1

            # A seeded historical forecast so the activity log is non-empty on
            # first load. The figure echoes the archetype's typical daytime load.
            typical = round(sum(s.cpu_pct for s in samples) / len(samples))
            session.add(
                Action(
                    id=str(uuid4()),
                    host_id=host.id,
                    ts=base + timedelta(days=_SEED_DAYS),
                    action_type="FORECAST",
                    detail=(
                        f"Forecast CPU +60m on {hostname}: ~{typical}% "
                        f"({arch.label})"
                    ),
                )
            )
        await session.commit()
        return added
