#!/usr/bin/env bash
#
# MetricLens AI — Deterministic & Idempotent Test Data Generator
# ------------------------------------------------------------------------------
# Seeds the time-series schema defined in ./docs/04_database_design.md and
# ./scripts/schema.sql: HOSTS, METRICS, FORECASTS, RECOMMENDATIONS.
#
# Design goals (enforced, not aspirational):
#   * DETERMINISTIC : Identifiers, strings and timestamps derive from a row
#                     index via md5 / fixed profiles, never from $RANDOM.
#                     Re-running produces byte-identical SQL.
#   * IDEMPOTENT    : hosts/forecasts/recommendations use ON CONFLICT (id);
#                     metrics use ON CONFLICT (host_id, ts). Running N times
#                     equals running once. No existing rows are mutated.
#   * ATOMIC        : The dataset is applied inside one transaction with
#                     ON_ERROR_STOP=1; partial failure rolls back.
#   * VERIFIABLE    : With no database reachable, a full SQL artifact is still
#                     emitted to ./scripts/seed_data.sql for CI inspection.
#
# Boundary Value Analysis / Equivalence Partitioning (per docs/07):
#   * HOSTS   : minimum sizing (1 vCPU / 256 MB) and large sizing; all 3
#               environment classes (PROD/STAGING/DEV).
#   * METRICS : pinned 0.00% and 100.00% CPU boundary samples; a realistic
#               24-hour seasonal profile (trough at night, peak midday).
#   * FORECAST: one forecast per measured metric class.
#
# Usage:
#   ./scripts/generate_test_data.sh                       # write SQL artifact
#   DATABASE_URL=postgres://... ./scripts/generate_test_data.sh --apply
#   DATABASE_URL=postgres://... ./scripts/generate_test_data.sh --apply --schema
#   NUM_HOSTS=8 SAMPLES_PER_HOST=96 ./scripts/generate_test_data.sh
#
# Environment:
#   DATABASE_URL      libpq connection string. Required with --apply.
#   NUM_HOSTS         Hosts to synthesise            (default 4).
#   SAMPLES_PER_HOST  Metric samples per host        (default 48, hourly).
#   OUTPUT_SQL        SQL artifact path              (default ./scripts/seed_data.sql).
# ------------------------------------------------------------------------------

set -euo pipefail

NUM_HOSTS="${NUM_HOSTS:-4}"
SAMPLES_PER_HOST="${SAMPLES_PER_HOST:-48}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT_SQL="${OUTPUT_SQL:-${SCRIPT_DIR}/seed_data.sql}"
SCHEMA_SQL="${SCRIPT_DIR}/schema.sql"

APPLY=0
APPLY_SCHEMA=0
for arg in "$@"; do
    case "$arg" in
        --apply)  APPLY=1 ;;
        --schema) APPLY_SCHEMA=1 ;;
        -h|--help) sed -n '2,46p' "${BASH_SOURCE[0]}"; exit 0 ;;
        *) echo "Unknown argument: ${arg}" >&2; exit 2 ;;
    esac
done

# --- Deterministic primitives -------------------------------------------------
# Stable RFC-4122-shaped UUID derived purely from a seed string.
det_uuid() {
    local hash
    hash="$(printf '%s' "$1" | md5sum | cut -c1-32)"
    printf '%s-%s-%s-%s-%s' \
        "${hash:0:8}" "${hash:8:4}" "${hash:12:4}" "${hash:16:4}" "${hash:20:12}"
}

# Deterministic timestamp: base epoch advanced by N minutes (UTC).
BASE_EPOCH=1704067200 # 2024-01-01T00:00:00Z
det_ts() {
    date -u -d "@$(( BASE_EPOCH + $1 * 60 ))" +"%Y-%m-%d %H:%M:%S"
}

# SQL single-quote escaping (defensive; deterministic data is quote-free).
sql_str() { printf "'%s'" "${1//\'/\'\'}"; }

# Realistic 24-hour CPU utilisation profile (%) — diurnal seasonality:
# low overnight, ramp at 08:00, peak around 14:00, taper after 18:00.
DAILY_CPU=(12 10 9 8 8 9 14 25 45 58 66 72 78 82 85 80 70 60 48 38 30 24 18 14)

# --- SQL artifact assembly ----------------------------------------------------
TMP_SQL="$(mktemp)"
trap 'rm -f "${TMP_SQL}"' EXIT

{
    echo "-- MetricLens AI seed data — generated by scripts/generate_test_data.sh"
    echo "-- Deterministic & idempotent. Safe to re-apply any number of times."
    echo "BEGIN;"
    echo
} >> "${TMP_SQL}"

declare -a HOST_IDS=()
declare -a HOST_VCPU=()
declare -a HOST_MEM=()

# ---- HOSTS -------------------------------------------------------------------
# Host 1 pins the minimum sizing boundary (1 vCPU / 256 MB). Subsequent hosts
# ramp sizing and cycle the environment enum so every class is represented.
ENVIRONMENTS=("PROD" "STAGING" "DEV")
for i in $(seq 1 "${NUM_HOSTS}"); do
    hid="$(det_uuid "host-${i}")"
    HOST_IDS+=("${hid}")
    env="${ENVIRONMENTS[$(( (i - 1) % 3 ))]}"
    if (( i == 1 )); then
        vcpu=1; mem=256          # minimum sizing boundary
    else
        vcpu=$(( 2 ** ((i % 5) + 1) ))   # 4,8,16,32,2,...
        mem=$(( vcpu * 2048 ))
    fi
    HOST_VCPU+=("${vcpu}")
    HOST_MEM+=("${mem}")
    printf 'INSERT INTO hosts (id, hostname, environment, vcpu_count, memory_mb, created_at) VALUES (%s, %s, %s, %s, %s, %s) ON CONFLICT (id) DO NOTHING;\n' \
        "$(sql_str "${hid}")" \
        "$(sql_str "$(printf 'host-%s-%02d' "$(echo "${env}" | tr '[:upper:]' '[:lower:]')" "${i}")")" \
        "$(sql_str "${env}")" "${vcpu}" "${mem}" \
        "$(sql_str "$(det_ts "${i}")")" \
        >> "${TMP_SQL}"
done

# ---- METRICS -----------------------------------------------------------------
# Per host: SAMPLES_PER_HOST hourly samples following the diurnal profile plus a
# small per-host deterministic offset and a slow linear trend. Two pinned
# boundary samples (0.00% and 100.00% CPU) are injected for the first host.
for h in $(seq 0 $(( NUM_HOSTS - 1 ))); do
    hid="${HOST_IDS[$h]}"
    host_offset=$(( h * 5 ))
    for s in $(seq 0 $(( SAMPLES_PER_HOST - 1 ))); do
        hour=$(( s % 24 ))
        base="${DAILY_CPU[$hour]}"
        trend=$(( s / 12 ))                       # +1% per half-day of history
        jitter=$(( (s * 7 + h * 3) % 6 - 3 ))     # deterministic [-3,+2]
        cpu=$(( base + host_offset + trend + jitter ))
        (( cpu < 0 )) && cpu=0
        (( cpu > 100 )) && cpu=100
        mem=$(( cpu * 70 / 100 + 20 ))            # memory tracks CPU, floor 20
        (( mem > 100 )) && mem=100
        net_in=$(( cpu * 120 + 50 ))
        net_out=$(( cpu * 80 + 30 ))
        ts="$(det_ts "$(( 10000 + h * 100000 + s * 60 ))")"
        printf 'INSERT INTO metrics (host_id, ts, cpu_pct, mem_pct, net_in_kbps, net_out_kbps) VALUES (%s, %s, %s.00, %s.00, %s.00, %s.00) ON CONFLICT (host_id, ts) DO NOTHING;\n' \
            "$(sql_str "${hid}")" "$(sql_str "${ts}")" "${cpu}" "${mem}" "${net_in}" "${net_out}" \
            >> "${TMP_SQL}"
    done
done

# Pinned CPU boundary samples on host #1 (idle 0% and saturated 100%).
bhid="${HOST_IDS[0]}"
printf 'INSERT INTO metrics (host_id, ts, cpu_pct, mem_pct, net_in_kbps, net_out_kbps) VALUES (%s, %s, 0.00, 20.00, 50.00, 30.00) ON CONFLICT (host_id, ts) DO NOTHING;\n' \
    "$(sql_str "${bhid}")" "$(sql_str "$(det_ts 99000)")" >> "${TMP_SQL}"
printf 'INSERT INTO metrics (host_id, ts, cpu_pct, mem_pct, net_in_kbps, net_out_kbps) VALUES (%s, %s, 100.00, 100.00, 12050.00, 8030.00) ON CONFLICT (host_id, ts) DO NOTHING;\n' \
    "$(sql_str "${bhid}")" "$(sql_str "$(det_ts 99060)")" >> "${TMP_SQL}"

# ---- FORECASTS ---------------------------------------------------------------
# One forecast per measured metric class per host, MAPE within the 15% target.
METRIC_CLASSES=("CPU" "MEM" "NET_IN" "NET_OUT")
for h in $(seq 0 $(( NUM_HOSTS - 1 ))); do
    hid="${HOST_IDS[$h]}"
    idx=0
    for m in "${METRIC_CLASSES[@]}"; do
        fid="$(det_uuid "forecast-${h}-${m}")"
        pv=$(( 60 + h * 4 + idx * 3 ))
        lb=$(( pv - 8 ))
        ub=$(( pv + 8 ))
        mape=$(( 7 + (h + idx) % 8 ))             # 7..14 (<= 15% target)
        printf 'INSERT INTO forecasts (id, host_id, metric, generated_at, horizon_minutes, model, predicted_value, lower_bound, upper_bound, mape) VALUES (%s, %s, %s, %s, 60, %s, %s.00, %s.00, %s.00, %s.00) ON CONFLICT (id) DO NOTHING;\n' \
            "$(sql_str "${fid}")" "$(sql_str "${hid}")" "$(sql_str "${m}")" \
            "$(sql_str "$(det_ts "$(( 200000 + h * 100 + idx ))")")" \
            "$(sql_str 'STL_HOLTWINTERS')" "${pv}" "${lb}" "${ub}" "${mape}" \
            >> "${TMP_SQL}"
        idx=$(( idx + 1 ))
    done
done

# ---- RECOMMENDATIONS ---------------------------------------------------------
# One IP-derived resizing recommendation per host. Downsizing is proposed where
# headroom exists; SLO confidence is pinned at the 99.90% target.
for h in $(seq 0 $(( NUM_HOSTS - 1 ))); do
    hid="${HOST_IDS[$h]}"
    cur_vcpu="${HOST_VCPU[$h]}"
    cur_mem="${HOST_MEM[$h]}"
    rec_vcpu=$(( cur_vcpu > 1 ? cur_vcpu / 2 : 1 ))
    rec_mem=$(( cur_mem > 256 ? cur_mem / 2 : 256 ))
    if (( cur_vcpu > 0 )); then
        saving=$(( (cur_vcpu - rec_vcpu) * 100 / cur_vcpu ))
    else
        saving=0
    fi
    rid="$(det_uuid "rec-${h}")"
    printf 'INSERT INTO recommendations (id, host_id, generated_at, current_vcpu, recommended_vcpu, current_memory_mb, recommended_memory_mb, est_cost_saving_pct, slo_confidence) VALUES (%s, %s, %s, %s, %s, %s, %s, %s.00, 99.90) ON CONFLICT (id) DO NOTHING;\n' \
        "$(sql_str "${rid}")" "$(sql_str "${hid}")" \
        "$(sql_str "$(det_ts "$(( 300000 + h ))")")" \
        "${cur_vcpu}" "${rec_vcpu}" "${cur_mem}" "${rec_mem}" "${saving}" \
        >> "${TMP_SQL}"
done

{
    echo
    echo "COMMIT;"
} >> "${TMP_SQL}"

# --- Materialise the artifact (always) ----------------------------------------
cp "${TMP_SQL}" "${OUTPUT_SQL}"
total_metrics=$(( NUM_HOSTS * SAMPLES_PER_HOST + 2 ))
echo "SQL artifact written: ${OUTPUT_SQL}"
echo "  HOSTS=${NUM_HOSTS}  METRICS=${total_metrics}  FORECASTS=$(( NUM_HOSTS * 4 ))  RECOMMENDATIONS=${NUM_HOSTS}"

# --- Apply to the database (only with --apply) --------------------------------
if (( APPLY == 1 )); then
    if [[ -z "${DATABASE_URL:-}" ]]; then
        echo "Error: --apply requires DATABASE_URL to be set." >&2
        echo '  e.g. export DATABASE_URL="postgresql://user:pass@host:5432/metriclens"' >&2
        exit 1
    fi
    if ! command -v psql >/dev/null 2>&1; then
        echo "Error: --apply requires the 'psql' client on PATH." >&2
        exit 1
    fi
    if (( APPLY_SCHEMA == 1 )); then
        echo "Applying schema (idempotent DDL)..."
        psql "${DATABASE_URL}" --set ON_ERROR_STOP=1 --quiet --no-password -f "${SCHEMA_SQL}"
    fi
    echo "Applying seed data to the target database (single transaction)..."
    psql "${DATABASE_URL}" --set ON_ERROR_STOP=1 --quiet --no-password -f "${OUTPUT_SQL}"
    echo "Seed data applied successfully. Idempotent: safe to re-run."
else
    echo "Dry run complete. Re-run with --apply (and DATABASE_URL) to load the database."
fi
